export type SyncDiagnostic = { code: string; en: string; fr: string; actionEn: string; actionFr: string };
const diagnostic = (code: string, en: string, fr: string, actionEn: string, actionFr: string): SyncDiagnostic => ({ code, en, fr, actionEn, actionFr });
export function synchronizationDiagnostic(input: {
  online: boolean; available: boolean; configured: boolean; ready: boolean;
  source?: { code: string; checked_at: number } | null; now?: number;
}): SyncDiagnostic {
  if (!input.online) return diagnostic('community_offline', 'Community is not connected to Cloud.', 'Community n’est pas connecté au Cloud.', 'Keep Community running and check its Internet connection.', 'Gardez Community démarré et vérifiez sa connexion Internet.');
  if (!input.available) return diagnostic('local_status_unavailable', 'Local synchronization could not be verified.', 'La synchronisation locale n’a pas pu être vérifiée.', 'Refresh this page. Check the local service if the error persists.', 'Actualisez cette page. Vérifiez le service local si l’erreur persiste.');
  if (!input.configured) return diagnostic('connector_not_configured', 'The connector source is not configured.', 'La source du connecteur n’est pas configurée.', 'Check this store’s endpoint, identifier and connector API test.', 'Vérifiez l’endpoint, l’identifiant et le test API du connecteur de cette boutique.');
  const age = (input.now ?? Date.now()) - (input.source?.checked_at ?? 0);
  if (!input.source || age > 120_000 || age < -30_000) return diagnostic('source_status_stale', 'No recent connector check is available. Cron status is unknown.', 'Aucun contrôle récent du connecteur n’est disponible. L’état du cron est inconnu.', 'Keep Community online; check the connector API test and cron status in the store. Missing events alone do not prove cron has stopped.', 'Gardez Community en ligne ; vérifiez le test API et l’état du cron dans la boutique. L’absence de signaux ne prouve pas à elle seule que le cron est arrêté.');
  if (input.source.code === 'source_auth_rejected') return diagnostic('source_auth_rejected', 'The store refused connector authentication (HTTP 401/403).', 'La boutique a refusé l’authentification du connecteur (HTTP 401/403).', 'Check the store identifier, connector key and store access rules, then run Test API. Do not rotate a working key blindly.', 'Vérifiez l’identifiant boutique, la clé connecteur et les règles d’accès, puis lancez Test API. Ne remplacez pas une clé fonctionnelle à l’aveugle.');
  if (input.source.code === 'source_signature_rejected') return diagnostic('source_signature_rejected', 'The connector response could not be authenticated.', 'La réponse du connecteur n’a pas pu être authentifiée.', 'Verify the connector version and pairing. Never disable signature verification.', 'Vérifiez la version et l’association du connecteur. Ne désactivez jamais la vérification de signature.');
  if (input.source.code !== 'ok') return diagnostic('source_unavailable', 'The connector could not be synchronized.', 'Le connecteur n’a pas pu être synchronisé.', 'Check store availability, HTTPS and Test API. Automatic retries continue while Community is running.', 'Vérifiez la disponibilité de la boutique, HTTPS et Test API. Les tentatives automatiques continuent tant que Community fonctionne.');
  if (!input.ready) return diagnostic('source_catching_up', 'Connector synchronization is in progress.', 'La synchronisation du connecteur est en cours.', 'Keep Community running and check the next refresh.', 'Gardez Community démarré et contrôlez la prochaine actualisation.');
  return diagnostic('source_verified', 'The latest connector synchronization succeeded.', 'La dernière synchronisation du connecteur a réussi.', 'This does not confirm the store cron or an email delivery. Check those separately.', 'Cela ne confirme ni le cron de la boutique ni un envoi d’email. Vérifiez-les séparément.');
}
